config/routes.rb
Reports::Application.routes.draw do

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      get '/bug/:bug_id', to: 'projects#bug_info'
      get '/commit', to: 'projects#commit_info'
      get '/shortlog', to: 'projects#shortlog'
      resources :projects do
        get 'bugs_report', :on => :member
        get 'bugs_list', :on => :member
        get 'commits_report', :on => :member
        get 'commits_list', :on => :member
        get 'mailing_lists_report', :on => :member
        get 'messages_list', :on => :member
        get 'messages_of_month', :on => :member
        get 'message', :on => :member
        get 'project_report', :on => :member
        get 'irc_channels_report', :on => :member
      end
    end
  end

  scope "(:locale)" do
    get "admin/index"

    get "admin/", to: 'admin#index'

    get "admin/control_user"

    get '/bug/:bug_id', to: 'projects#bug_info'

    get '/commit', to: 'projects#commit_info'

    get '/shortlog', to: 'projects#shortlog'

    devise_for :users

    resources :custom_reports do
      Constants::TYPES_TO_REPORT_TITLES.values.each do |name|
        get "#{name}_report", :on => :member
      end
    end

    get 'kde/', to: 'kde#index', as: :kde
    get 'kde/commits_report', to: 'kde#commits_report', as: :kde_commits_report
    get 'kde/mailing_lists_report', to: 'kde#mailing_lists_report', as: :kde_mailing_lists_report
    get 'kde/irc_channels_report', to: 'kde#irc_channels_report', as: :kde_irc_channels_report

    resources :projects do
      get 'bugs_report', :on => :member
      get 'bugs_list', :on => :member
      get 'bug/:bug_id', :on => :member, :as => :bug, to: 'projects#bug_info'
      get 'repository/:product/:branch/:directory', :on => :member, to: 'projects#repository',as: :repo_path , product: /.+\.git/, directory: /.+/, branch: /[^\/]+/
      get 'repository/:product(/:branch)', :on => :member, to: 'projects#repository',as: :full_repository, product: /.+\.git/, branch: /[^\/]+/
      get 'repository', :on => :member
      get 'blob/:product/:sha/:blob', :on => :member, to: 'projects#show_blob', as: :blob , product: /.+\.git/, blob: /.+/
      get 'commits_report', :on => :member
      get 'commits_per_day', :on => :member
      get 'review_requests_report', :on => :member
      get 'commits_list/:product', :on => :member , to: 'projects#commits_list', product: /.+\.git/
      get 'commits_list', :on => :member
      get 'commit/:product:commit_sha', to: 'projects#commit_info', :on => :member , as: :commit, product: /.+\.git/
      get 'product/:product/branch/*branch', to: 'projects#branch', on: :member, as: :branch, product: /.+\.git/, branch: /.+/
      get 'mailing_lists_report', :on => :member
      get 'mailing_messages_per_day', :on => :member
      get 'messages_list', :on => :member
      get 'messages_list/:mlist/:month/:index', on: :member, to: 'projects#message', as: :message, mlist: /.+\.mbox/
      get 'messages_list/:mlist/:month', on: :member, to: 'projects#messages_of_month', as: :messages_of_month, mlist: /.+\.mbox/
      get 'messages_list/:mlist', :on => :member , to: 'projects#messages_list', as: :messages_list_mbox, mlist: /.+\.mbox/
      get 'project_report', :on => :member
      get 'irc_channels_report', :on => :member
      get 'irc_messages_per_day', :on => :member
      get 'facebook_pages_report', :on => :member
      get 'twitter_report', :on => :member
      get 'google_plus_report', :on => :member
      get 'forums_report', :on => :member
      get 'forums_topics_list', :on => :member
      get 'planet_report', :on => :member
      get 'dot_report', :on => :member
      get 'wiki_report', :on => :member
      get 'builds_report', :on => :member
    end

    get "home/index"

    resources :news

    match '/:locale' => 'home#index', via: [:get, :post]
    root :to => 'home#index'
  end

end

app/models/news.rb
class News
  include Mongoid::Document
  resourcify
  belongs_to :user
  field :title
  field :content
  field :created_at, type: Date, default: Date.today
  
  validates :title , :presence => true
  validates :content , :presence => true
  #self.per_page = 5
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  
  # Add authorization using cancan.
  load_and_authorize_resource
  
  # GET /news
  # GET /news.json
  def index
    @news = News.order_by(:created_at.desc).page(params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  def new
    @news = News.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)
    @news.user = current_user
    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render json: @news, status: :created, location: @news }
      else
        format.html { render action: "new" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.json
  def update
    @news = News.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end
  
  private
    
    def news_params
      params.require(:news).permit(:title, :content)
    end
  
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div class="alert alert-error">
      <h3 style="color:red;"><%= pluralize(@news.errors.count, "error") %> <%= t('prohibited_this_news_from_being_saved') %>:</h3>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %><br />
    <%= f.text_field :title , :class => 'field span12' %>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %><br />
    <%= f.cktext_area :content , :class => 'field span12' %>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), news_index_path, :class => 'btn' %>
  </div>
<% end %>
<% content_for :early_load do %>
	<script src="http://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.0.1/ckeditor.js"></script>
<% end %>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<% content_for(:title, t('news') ) %>
<div class="page-header">
	<% if can? :create, News %>
		<%= link_to new_news_path, :class => 'btn btn-primary' do %>
		    <i class="icon-plus icon-white"></i>
		    <%= t :new_news %>
		<% end %>
	<% end %>
  <h1>
	<%= t("latest_news") %>
  </h1>
</div>
<% @news.each do |news| %>
	<div class = "well well-mini">
		<h2>
			<%= link_to news.title,news %>
		</h2>
		<%= t('by') + ' ' + news.user.login %> <%= time_ago_in_words(news.created_at) + ' ' + t('ago') %>
		<hr>
		<%=raw news.content[0..1500] %>
		<%= link_to t('see_more')+'...',news %>
	</div>
<% end %>
<%= will_paginate @news, :renderer => BootstrapPagination::Rails %>

app/views/news/new.html.erb
<% content_for(:title, t('new_news') ) %>
<h1><%= t :new_news %></h1>

<%= render 'form' %>

app/views/news/show.html.erb
<% content_for(:title, @news.title ) %>
<div class="page-header">
	<button class="btn" onclick="history.go(-1);return true;">
    <i class="icon-list-alt"></i>
    <%= t :back %>
</button>
<% if can? :update, @news %>
	<%= link_to edit_news_path(@news), :class => 'btn btn-primary' do %>
	    <i class="icon-pencil icon-white"></i>
		<%= t :edit %>
	<% end %>
<% end %>
  <h1>
	<%= @news.title %>
  </h1>
	<%= t('by') + ' ' + @news.user.login %> <%= time_ago_in_words(@news.created_at) + ' ' + t('ago') %>
</div>
<div class = "thumbnail">
	<%= raw @news.content %>
</div>