config/routes.rb
Reports::Application.routes.draw do

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      get '/bug/:bug_id', to: 'projects#bug_info'
      get '/commit', to: 'projects#commit_info'
      get '/shortlog', to: 'projects#shortlog'
      resources :projects do
        get 'bugs_report', :on => :member
        get 'bugs_list', :on => :member
        get 'commits_report', :on => :member
        get 'commits_list', :on => :member
        get 'mailing_lists_report', :on => :member
        get 'messages_list', :on => :member
        get 'messages_of_month', :on => :member
        get 'message', :on => :member
        get 'project_report', :on => :member
        get 'irc_channels_report', :on => :member
      end
    end
  end

  scope "(:locale)" do
    get "admin/index"

    get "admin/", to: 'admin#index'

    get "admin/control_user"

    get '/bug/:bug_id', to: 'projects#bug_info'

    get '/commit', to: 'projects#commit_info'

    get '/shortlog', to: 'projects#shortlog'

    devise_for :users

    resources :custom_reports do
      Constants::TYPES_TO_REPORT_TITLES.values.each do |name|
        get "#{name}_report", :on => :member
      end
    end

    get 'kde/', to: 'kde#index', as: :kde
    get 'kde/commits_report', to: 'kde#commits_report', as: :kde_commits_report
    get 'kde/mailing_lists_report', to: 'kde#mailing_lists_report', as: :kde_mailing_lists_report
    get 'kde/irc_channels_report', to: 'kde#irc_channels_report', as: :kde_irc_channels_report

    resources :projects do
      get 'bugs_report', :on => :member
      get 'bugs_list', :on => :member
      get 'bug/:bug_id', :on => :member, :as => :bug, to: 'projects#bug_info'
      get 'repository/:product/:branch/:directory', :on => :member, to: 'projects#repository',as: :repo_path , product: /.+\.git/, directory: /.+/, branch: /[^\/]+/
      get 'repository/:product(/:branch)', :on => :member, to: 'projects#repository',as: :full_repository, product: /.+\.git/, branch: /[^\/]+/
      get 'repository', :on => :member
      get 'blob/:product/:sha/:blob', :on => :member, to: 'projects#show_blob', as: :blob , product: /.+\.git/, blob: /.+/
      get 'commits_report', :on => :member
      get 'commits_per_day', :on => :member
      get 'review_requests_report', :on => :member
      get 'commits_list/:product', :on => :member , to: 'projects#commits_list', product: /.+\.git/
      get 'commits_list', :on => :member
      get 'commit/:product:commit_sha', to: 'projects#commit_info', :on => :member , as: :commit, product: /.+\.git/
      get 'product/:product/branch/*branch', to: 'projects#branch', on: :member, as: :branch, product: /.+\.git/, branch: /.+/
      get 'mailing_lists_report', :on => :member
      get 'mailing_messages_per_day', :on => :member
      get 'messages_list', :on => :member
      get 'messages_list/:mlist/:month/:index', on: :member, to: 'projects#message', as: :message, mlist: /.+\.mbox/
      get 'messages_list/:mlist/:month', on: :member, to: 'projects#messages_of_month', as: :messages_of_month, mlist: /.+\.mbox/
      get 'messages_list/:mlist', :on => :member , to: 'projects#messages_list', as: :messages_list_mbox, mlist: /.+\.mbox/
      get 'project_report', :on => :member
      get 'irc_channels_report', :on => :member
      get 'irc_messages_per_day', :on => :member
      get 'facebook_pages_report', :on => :member
      get 'twitter_report', :on => :member
      get 'google_plus_report', :on => :member
      get 'forums_report', :on => :member
      get 'forums_topics_list', :on => :member
      get 'planet_report', :on => :member
      get 'dot_report', :on => :member
      get 'wiki_report', :on => :member
      get 'builds_report', :on => :member
    end

    get "home/index"

    resources :news

    match '/:locale' => 'home#index', via: [:get, :post]
    root :to => 'home#index'
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
  def build_bug_products_and_jobs(project)
    @bug_products = Project.list_selectable_products
    @build_jobs = BuildDataManager.all_jobs_selection_array
    project
  end

  def render_property name,value
    return render :partial => "property", :locals => {
     :name => name, :value => value
    }
  end

  def render_commits_charts type, to_plot, unloaded = nil
    types = {true => "tabbed_pie_chart_display", false => "single_pie_chart_display"}
    masks = {
      "commits" => ["commits","author"],
      "mailing_messages" => ["messages","sender"],
      "irc_messages" => ["messages","sender"],
      "facebook_posts" => [nil,"user"],
      "twitter_tweets" => ["retweets", "user"],
      "google_plus_posts" => [nil,"user"],
      "forum_posts" => ["posts","poster"],
      "planet_posts" => ["posts","poster"],
      "dot_posts" => [nil,"posts"],
      "review_requests" => ["requests","contributor"],
    }
    WikiDataManager.explorable_sites.each do |site|
      masks["#{site}_wiki"] = ["revisions", "contributor_for_#{site}"]
    end
    BuildDataManager.all_stats.each do |status|
      masks["#{status}_build"] = ["builds", "contributor"]
    end
    if masks[type][0]
      title = "#{to_plot}_#{masks[type][0]}_per_#{masks[type][1]}"
    else
      title = "#{to_plot}_per_#{masks[type][1]}"
    end
    return render :partial => types[@project.drawables[type][to_plot]], :locals => {
        :title => title,
        :type => type,
        :to_plot => to_plot,
        :unloaded => unloaded
      }
  end
  
  def render_standard_pie_charts path, title, tabbed, unloaded = nil
    types = {true => "tabbed_pie_chart", false => "single_pie_chart"}
    return render :partial => types[tabbed], :locals => {
        :path => path,
        :title => title,
        :unloaded => unloaded
      }
  end

  def render_bugs_chart to_plot, unloaded = nil
    types = {true => "tabbed_pie_chart_display", false => "single_pie_chart_display"}
    return render :partial => types[@project.drawables["bugs"][to_plot]], :locals => {
        :title => "bugs_by_#{to_plot}",
        :type => "bugs",
        :to_plot => to_plot,
        :unloaded => unloaded
      }
  end

  # Draws a single chart with single line.
  def render_objects_chart type, approx = "sum", decimals = nil, custom_agg = false
    #TODO: This hash should be moved out of here.
    types = {
      "commits" => ["number_of_commits","objects"],
      "mailing_messages" => ["number_of_messages","objects"],
      "irc_messages" => ["number_of_messages","objects"],
      "total-bugs" => ["total_number_of_bugs","total_created"],
      "open-bugs" => ["total_number_of_open_bugs","net_open"],
      "still-open-bugs" => ["number_of_reported_bugs_still_open","still_open"],
      "average_close_time-bugs" => ["average_number_of_days_to_close_bugs_closed_in_less_than_a_year","average_close_time"],
      "resolved_after_a_year-bugs" => ["number_of_bugs_closed_after_a_year","resolved_after_a_year"],
      "average_first_reply-mailing_messages" => ["average_number_of_hours_to_first_reply","average_time_to_first_reply"],
      "average_first_reply-irc_messages" => ["average_number_of_hours_to_first_reply","average_time_to_first_reply"],
      "average_first_reply-forum_posts" => ["average_number_of_hours_to_first_reply","average_time_to_first_reply"],
      "average_hours_to_fix-build" => ["average_number_of_hours_to_fix","average_hours_to_fix"],
      "average_tries_to_fix-build" => ["average_number_of_tries_to_fix","average_tries_to_fix"],
      "comments-facebook_posts" => ["number_of_comments","comments"],
      "replies-google_plus_posts" => ["number_of_replies","replies"],
      "retweets_users-twitter_tweets" => ["retweets_by_users","retweets-users"],
      "planet_posts" => ["number_of_posts","objects"],
      "average_close_time-review_requests" => ["average_number_of_days_to_close_reviews","average_close_time"],
      "closed_after_a_year-review_requests" => ["number_of_reviews_closed_after_a_year","closed_after_a_year"],
      }
      WikiDataManager.explorable_sites.each do |wiki|
        types["users_registered-#{wiki}_wiki"] = ["number_of_users_registered-#{wiki}","registrations"]
        types["revisions-#{wiki}_wiki"] = ["number_of_revisions-#{wiki}","revisions"]
      end
      label = types[type][0].split("-").first
    return render :partial => "full_objects_line_graph", :locals => {
      :objects => type.split("-").last,
      :line => types[type][1],
      # Title and y_label are the same in these graphs except for that title should have an extra "_over_time"
      :title => types[type][0],
      :y_label => label,
      :lang_label => label + "_over_time",
      :approx => approx,
      :decimals => decimals,
      :custom_agg => custom_agg
    }
  end

  # Draws multiple lines in the a single chart.
  def render_multiple_objects_chart type, approx
    types = {
      "bugs" => "rep_res",
      "commits" => "lines",
      "facebook_posts" => "posts",
      "tweets-twitter_tweets" => "tweets",
      "retweets_page-twitter_tweets" => "retweets-page",
      "google_plus_posts" => "objects",
      "forum_posts" => "objects",
      "dot_posts" => "objects",
      "review_requests" => "objects",
      "build" => "objects"
    }
    titles = {
      "bugs" => "number_of_bugs",
      "commits" => "number_of_lines",
      "facebook_posts" => "numbers",
      "tweets-twitter_tweets" => "tweets_by_page",
      "retweets_page-twitter_tweets" => "retweets_by_page",
      "google_plus_posts" => "numbers",
      "forum_posts" => "numbers",
      "dot_posts" => "numbers",
      "review_requests" => "numbers",
      "build" => "build"
    }
    return render :partial => "full_objects_multiple_line_graph", :locals => {
      :objects => type.split("-").last,
      :lines => types[type],
      :approx => approx,
      :title => titles[type] + "_over_time",
      :y_label => titles[type],
    }
  end

  def render_doers_chart type
    types = {
      "commits" => "authors",
      "mailing_messages" => "senders",
      "irc_messages" => "senders",
      "facebook_posts" => "users",
      "twitter_tweets" => "retweeters",
      "google_plus_posts" => "users",
      "forum_posts" => "posters",
      "planet_posts" => "posters",
      "dot_posts" => "posters",
      "review_requests" => "requesters"
    }
    WikiDataManager.explorable_sites.each do |wiki|
      types["#{wiki}_wiki"] = "editors-#{wiki}"
    end
    label = types[type].split("-").first
    return render :partial => "full_doers_line_graph", :locals => {
      :title => types[type],
      :y_label => label,
      :lang_label => label + "_over_time",
      :type => type
        }
  end

  def render_json_hash to_render
    res = ""
    to_render.each do |k,v|
      res += '"' + k.to_s + '":'
      res += '"' if v.class == String
      res += v.to_s.gsub(/"/,'\\"')
      res += '"' if v.class == String
      res += ","
    end
    return res[0...-1]
  end

  def render_xml_hash to_render
    res = to_render.to_xml(:skip_instruct => true)
    return res[6...-8]
  end

end

app/views/projects/_ajax_pie.html.erb
$(function() {

	<% if (unloaded ||= nil) %>
		$('a[href="#<%= unloaded %>"]').one("click",function(){
	<% end %>
	
	$.getJSON("<%= path %><%= extra ||= "" %>.json", function(data) {
		var final_data;
		if (data.constructor == Array) {
			final_data = data;
			Highcharts.setOptions({
			colors: [
			   '#4572A7',
			   '#AA4643', 
			   '#89A54E', 
			   '#80699B', 
			   '#3D96AE', 
			   '#DB843D', 
			   '#92A8CD', 
			   '#A47D7C', 
			   '#B5CA92'
			]
			});
		}
		else {
			final_data = data["data"];
			Highcharts.setOptions({
		     colors: data["colors"]
		    });
		}
	      new Highcharts.Chart({
	      chart: {
	  renderTo: <%= target %>
	      },
	      title: {
	  text: "<%= title %>"
	      },
	      tooltip: {
	  pointFormat: '<b>{point.y}</b>',
	  percentageDecimals: 1
	      },
	      plotOptions: {
	  pie: {
	                    allowPointSelect: true,
	                    cursor: 'pointer',
	                    dataLabels: {
	                        enabled: true,
	                        color: '#000000',
	                        connectorColor: '#000000',
	                        formatter: function() {
	                            return '<b>'+ this.point.name +'</b>: '+ this.percentage.toFixed(1) +' %';
	                        }
	                    }
	             }
	      },
	      series: [{
	                type: 'pie',
	                name: '<%= title %>',
	                data: final_data
	            }]
	      });
   });
      <% if unloaded %>
		});
	  <% end %>
      
   });

app/views/projects/_commits_all_time.html.erb
$(function () {
	Highcharts.setOptions({
     colors: [
   '#4572A7', 
   '#AA4643', 
   '#89A54E', 
   '#80699B', 
   '#3D96AE', 
   '#DB843D', 
   '#92A8CD', 
   '#A47D7C', 
   '#B5CA92'
]
    });
  new Highcharts.StockChart({
    chart: { renderTo: '<%= t(title, :locale => :en).tr(" ", "_") %>' },
    title: { text: '<%= t(title) %>' },
    xAxis: { oridnal: false },
    yAxis: {
      title: { text: '<%= y_label %>' },
      min: 0,
    },
    plotOptions: {line: {
            connectNulls: false
        } },
    series: [
    <% series.each do |s| %>
    {
      name: "<%= s[:name] %>",
      pointInterval: <%= 24*60*60 * 1000 %>,
      pointStart: <%= s[:first_date] %>,
      fillColor : '#348AFA',
      data: <%= s[:data] %>,
      "dataGrouping": { "units": [ [ "day",[ 1 ] ],[ "month",[ 1 ] ],["year",[1]]],"approximation": "sum", "groupPixelWidth": 50 }
    },
    <% end %>
    ]
  });
});

app/views/projects/_full_objects_multiple_line_graph.html.erb
<div id="<%= title %>" style="text-align: center;"><img src="/images/ajax-loader.gif" /></div>
<% content_for :scripts do %>
	<script>
		<%= render :partial => "objects_multiple_line_graph", :locals => {
			:objects => objects,
			:lines => lines,
			:approx => approx,
			:title => title,
			:y_label => y_label,
			:first_date => @start_date,
			}
			 %>
	</script>
<% end %>

app/views/projects/_git_repos.html.erb
<div class ="thumbnail">
	<% @project.get_repos.each do |repo| %>
		<% repo_display = repo[0..-5] %>
		<div>
			<span class="btn-group">
				<span class="btn-group" data-toggle="buttons-radio">
					<button onclick="display_repo('git','<%= repo_display %>')" class="btn active">Git</button>
					<button onclick="display_repo('http','<%= repo_display %>')" class="btn">HTTP</button>
					<button onclick="display_repo('ssh','<%= repo_display %>')" class="btn">SSH</button>
					<button onclick="display_repo('tarball','<%= repo_display %>')" class="btn">Tarball</button>
				</span>
				<input type="text" id="repo_link" class="span2" style="width:40%;background-color:white;cursor: auto;height: 23px;margin-top: 5px;" onclick="this.select();" value="git clone git://anongit.kde.org/<%= repo_display %>" readonly="readonly">
				<button onclick="$('#repo_link').select();document.execCommand('copy');" class="btn">
				  Copy
				</button>
			</span>
			&nbsp;
			<b><span id="access_type"><%= t('read_only') %></span></b>
		</div>
	<% end %>
</div>
<% content_for :scripts do %>
	<script>
	function display_repo(protocol,repo) {
		switch(protocol) {
		case "git":
		  $("#repo_link").val("git clone git://anongit.kde.org/" + repo);
		  $("#access_type").text("<%= t('read_only') %>");
		  break;
		case "http":
		  $("#repo_link").val("git clone http://anongit.kde.org/" + repo);
		  $("#access_type").text("<%= t('read_only') %>");
		  break;
		case "ssh":
		  $("#repo_link").val("git clone git@git.kde.org:" + repo);
		  $("#access_type").text("<%= t('read_write') %>");
		  break;
		case "tarball":
		  $("#repo_link").val("wget -c http://anongit.kde.org/" + repo + "/" + repo + "-latest.tar.gz");
		  $("#access_type").text("<%= t('read_only') %>");
		  break;
		default:
			$("#repo_link").val("git clone git://anongit.kde.org/" + repo);
			$("#access_type").text("<%= t('read_only') %>");
		}
	}
	</script>
<% end %>

app/views/projects/_list_forums_topics.html.erb
<table class="table table-striped">
      <thead>
	<tr>
	  <th><%= t :title %></th>
	  <th><%= t :author %></th>
	  <th><%= t :date %></th>
	  <th><%= t :category %></th>
	</tr>
      </thead>
      <tbody>
	<% @posts.each do |post| %>
	  <tr>
	  	<td><%= link_to post.title, post.link %></a></td>
	    <td><%= post.author %></td>
	    <td><%= post.pubDate %></td>
	    <td><%= post.category.content %></td>
	  </tr>
	<% end %>
      </tbody>
</table>

app/views/projects/_list_messages_of_month.html.erb
<ul>
<% @messages.each do |message| %>
	<% if !message[3] || !@message_ids.include?(message[3]) %>
		<li><%= link_to Mail::Encodings.value_decode(message[0]).force_encoding('utf-8'), message_project_path(@project, params[:mlist], params[:month], message[1]) %></li>
		<%= render :partial => "replies_to_thread", :locals => { :message_id => message[2] } if message[2] %>
	<% end %>
<% end %>
</ul>

app/views/projects/_project_report.html.erb
<% data.each do |key,value| %>
	<% unless exclude.include?(key) %>
		<% if value.class == Array  || value.class == Hash %>
		    <h6><%= t(key) %>:</h6>
			<% if value.class == Array %>
				<% items = {"default" => value} %>
			<% else%>
				<% items = value %>
			<% end %>
			<% items.each do |comp,val| %>
				<%= comp unless items.keys.length == 1 %>
				<% next unless val.first %>
				<table class="table table-striped">
					<thead>
						<tr>	
							<% val.first.keys.each do |heading| %>
								<th><%= t(heading.to_s) %></th>
							<% end %>
						</tr>
					</thead>
					<tbody>
						<% val.each do |item| %>
							<tr>
									<% item.each do |k,property| %>
										<% if links ||= nil %>
											<% if links.keys.include?(k) %>
												<td><%= link_to property,links[k]+property.to_s %></td>
											<% else %>
												<td><%= property %></td>
											<% end %>
										<% else %>
											<td><%= property %></td>
										<% end %>
									<% end %>
							</tr>
						<% end %>
					</tbody>
				</table>
			<% end %>
		<% else %>
			<h6><%= t(key) %>: <%= value.to_s %></h6>
		<% end %>
	<% end %>
<% end %>

app/views/projects/_replies_to_thread.html.erb
<ul>
	<% @messages.each do |message| %>
		<% if message[3] == message_id %>
			<li><%= link_to Mail::Encodings.value_decode(message[0]).force_encoding('utf-8'),  message_project_path(@project, params[:mlist], params[:month], message[1]) %></li>
			<%= render :partial => "replies_to_thread", :locals => { :message_id => message[2] } if message[2] %>
		<% end %>
	<% end %>
</ul>

app/views/projects/_tabbed_pie_chart.html.erb
<ul class="nav nav-tabs">
  <li class="active"><a href="#top_10_<%= title %>" data-toggle="tab">Top 10</a></li>
  <li><a href="#all_<%= title %>" data-toggle="tab">All</a></li>
</ul>

<div id='<%= title %>' class="tab-content">
  <div class="tab-pane active" id="top_10_<%= title %>" style="text-align: center;"><img src="/images/ajax-loader.gif" /></div>
  <div class="tab-pane" id="all_<%= title %>" style="text-align: center;"><img src="/images/ajax-loader.gif" /></div>
</div>
<% content_for :scripts do %>
	<script>
		<%= render :partial => "ajax_pie", :locals => {
			:path => path,
			:target => "top_10_#{title}",
			:title => t(title.split("_for_").first),
			:extra => "_top_10",
			:unloaded => unloaded
			} 
			 %>
		<%= render :partial => "ajax_pie", :locals => {
			:path => path,
			:target => "all_#{title}",
			:title => t(title.split("_for_").first),
			:extra => "_all",
			:unloaded => "all_#{title}",
			} 
			 %>
	</script>
<% end %>

app/views/projects/_tabbed_pie_chart_display.html.erb
<ul class="nav nav-tabs">
  <li class="active"><a href="#top_10_<%= title %>" data-toggle="tab">Top 10</a></li>
  <li><a href="#all_<%= title %>" data-toggle="tab">All</a></li>
</ul>

<div id='<%= title %>' class="tab-content">
  <div class="tab-pane active" id="top_10_<%= title %>" style="text-align: center;"><img src="/images/ajax-loader.gif" /></div>
  <div class="tab-pane" id="all_<%= title %>" style="text-align: center;"><img src="/images/ajax-loader.gif" /></div>
</div>
<% content_for :scripts do %>
	<script>
		<%= render :partial => "ajax_pie_chart", :locals => {
			:target => "top_10_#{title}",
			:title => t(title.split("_for_").first),
			:to_plot => to_plot,
			:type => type,
			:extra => "_top_10",
			:unloaded => unloaded
			} 
			 %>
		<%= render :partial => "ajax_pie_chart", :locals => {
			:target => "all_#{title}",
			:title => t(title.split("_for_").first),
			:type => type,
			:to_plot => to_plot,
			:extra => "_all",
			:unloaded => "all_#{title}",
			} 
			 %>
	</script>
<% end %>

app/views/projects/commit_info.html.erb
<% content_for(:title, t('commit') + ' ' + @commit.sha[0..7]) %>
<div class="page-header">
	<%= render partial: 'top_bar_for_single_project', locals: { back_link: commits_list_project_path(@project) } %>
  <h1>
	<%= t('commit') + ' ' + @commit.to_s[0..7] + " - " + params[:product] %>
  </h1>
  
  <a target="_blank" href="http://quickgit.kde.org/?p=<%= params[:product] %>&a=commit&h=<%= @commit.sha.to_s %>">
  	<%= t :see_in_quickgit %>
  </a>
</div>

<table>      
	<%= render_property(t('author'), @commit.author.name + " [" + @commit.author.email + "]") %>
	<%= render_property(t('date'), @commit.author.date) %>
	<%= render_property(t('committer'), @commit.committer.name + " [" + @commit.committer.email + "]") %>
	<%= render_property(t('date'), @commit.committer.date) %>
	<%= render_property(t('commit'), @commit.sha) %>
	<%= render_property(t('comment'), @commit.message) %>
	<%= render_property(t('tree'), ("<a target='_blank' href='http://quickgit.kde.org/?p="+params[:product]+"&a=tree&h="+@commit.gtree.to_s+"&hb="+@commit.sha.to_s+"'>"+@commit.gtree.to_s+"</a>").html_safe) %>
	<%= render_property(t('snapshot'), (link_to("zip", "http://quickgit.kde.org/?p=#{@product}&a=snapshot&h=#{@commit.sha}&fmt=zip") + " | " +
	link_to("tar", "http://quickgit.kde.org/?p=#{@product}&a=snapshot&h=#{@commit.sha}&fmt=tar") + " | " +
	link_to("tar.gz", "http://quickgit.kde.org/?p=#{@product}&a=snapshot&h=#{@commit.sha}&fmt=tgz")).html_safe) %>
	<% @commit.parents.each do |parent| %> 
	<%= render_property(t('parent'), (link_to parent.to_s, commit_project_path(@project, params[:product], parent.to_s))) %>
	<% end %>
</table>
<hr>
<%
begin 
	diff = @commit.diff_parent.stats
rescue
end 
%>
<% if diff %>
	<div class = "thumbnail">
		<table>
			<%= render_property(t('files_changed'), diff[:total][:files]) %>
			<%= render_property(t('total_insertions'), diff[:total][:insertions]  ) %>
			<%= render_property(t('total_deletions'), diff[:total][:deletions]  ) %>
			<%= render_property(t('total_lines_changed'), diff[:total][:lines]  ) %>
		</table>
	</div>
	<% diff[:files].each do |k,v| %>
		<hr>
		<div class = "thumbnail">
			<table>
				<%= render_property(t('file'), k) %>
				<%= render_property(t('insertions'), v[:insertions]) %>
				<%= render_property(t('deletions'), v[:deletions]) %>
			</table>
		</div>
	<% end %>
<% end %>

app/views/projects/index.html.erb
<% if @project %>
	<% content_for(:title, @project.title) %>
<% else %>
	<% content_for(:title, t('projects')) %>
<% end %>
<div class="page-header">
	<% if @project %>
		<% unless @project.parent_id ||= nil %>
	  		<%= render partial: 'top_bar_for_single_project', locals: { back_link: projects_path } %>
	  	<% else %>
	  		<%= render partial: 'top_bar_for_single_project', locals: { back_link: project_path(Project.find(@project.parent_id)) } %>
	  	<% end %>
	<% else %>
		<% if can? :create, Project %>
		  	<%= link_to new_project_path, :class => 'btn btn-primary', 'data-no-turbolink' => true do %>
		    	<i class="icon-plus icon-white"></i>
		    	<%= t :new_project %>
			<% end %>
		<% end %>
	  	<h1>
	  		<%= t :listing_projects %>
	 	</h1>
 	<% end %>
</div>


<%= render 'list_projects' %>

app/views/projects/message.html.erb
<% content_for(:title, @message.subject) %>
<div class="page-header">
  <%= render partial: 'top_bar_for_single_project', locals: { back_link: messages_of_month_project_path(params[:id], params[:mlist], params[:month]) } %>
  <h1>
	<%= @message.subject %>
  </h1>
</div>
<div class="row">
	<div class = "span9">
		<%= render 'display_message' %>
	</div>
	<div class = "span3">
		<div class="well sidebar-nav">
			<ul class="nav nav-list">
				<%= render 'side_bar' %>
			</ul>
		</div>
	</div>				
</div>