config/routes.rb
Reports::Application.routes.draw do

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      get '/bug/:bug_id', to: 'projects#bug_info'
      get '/commit', to: 'projects#commit_info'
      get '/shortlog', to: 'projects#shortlog'
      resources :projects do
        get 'bugs_report', :on => :member
        get 'bugs_list', :on => :member
        get 'commits_report', :on => :member
        get 'commits_list', :on => :member
        get 'mailing_lists_report', :on => :member
        get 'messages_list', :on => :member
        get 'messages_of_month', :on => :member
        get 'message', :on => :member
        get 'project_report', :on => :member
        get 'irc_channels_report', :on => :member
      end
    end
  end

  scope "(:locale)" do
    get "admin/index"

    get "admin/", to: 'admin#index'

    get "admin/control_user"

    get '/bug/:bug_id', to: 'projects#bug_info'

    get '/commit', to: 'projects#commit_info'

    get '/shortlog', to: 'projects#shortlog'

    devise_for :users

    resources :custom_reports do
      Constants::TYPES_TO_REPORT_TITLES.values.each do |name|
        get "#{name}_report", :on => :member
      end
    end

    get 'kde/', to: 'kde#index', as: :kde
    get 'kde/commits_report', to: 'kde#commits_report', as: :kde_commits_report
    get 'kde/mailing_lists_report', to: 'kde#mailing_lists_report', as: :kde_mailing_lists_report
    get 'kde/irc_channels_report', to: 'kde#irc_channels_report', as: :kde_irc_channels_report

    resources :projects do
      get 'bugs_report', :on => :member
      get 'bugs_list', :on => :member
      get 'bug/:bug_id', :on => :member, :as => :bug, to: 'projects#bug_info'
      get 'repository/:product/:branch/:directory', :on => :member, to: 'projects#repository',as: :repo_path , product: /.+\.git/, directory: /.+/, branch: /[^\/]+/
      get 'repository/:product(/:branch)', :on => :member, to: 'projects#repository',as: :full_repository, product: /.+\.git/, branch: /[^\/]+/
      get 'repository', :on => :member
      get 'blob/:product/:sha/:blob', :on => :member, to: 'projects#show_blob', as: :blob , product: /.+\.git/, blob: /.+/
      get 'commits_report', :on => :member
      get 'commits_per_day', :on => :member
      get 'review_requests_report', :on => :member
      get 'commits_list/:product', :on => :member , to: 'projects#commits_list', product: /.+\.git/
      get 'commits_list', :on => :member
      get 'commit/:product:commit_sha', to: 'projects#commit_info', :on => :member , as: :commit, product: /.+\.git/
      get 'product/:product/branch/*branch', to: 'projects#branch', on: :member, as: :branch, product: /.+\.git/, branch: /.+/
      get 'mailing_lists_report', :on => :member
      get 'mailing_messages_per_day', :on => :member
      get 'messages_list', :on => :member
      get 'messages_list/:mlist/:month/:index', on: :member, to: 'projects#message', as: :message, mlist: /.+\.mbox/
      get 'messages_list/:mlist/:month', on: :member, to: 'projects#messages_of_month', as: :messages_of_month, mlist: /.+\.mbox/
      get 'messages_list/:mlist', :on => :member , to: 'projects#messages_list', as: :messages_list_mbox, mlist: /.+\.mbox/
      get 'project_report', :on => :member
      get 'irc_channels_report', :on => :member
      get 'irc_messages_per_day', :on => :member
      get 'facebook_pages_report', :on => :member
      get 'twitter_report', :on => :member
      get 'google_plus_report', :on => :member
      get 'forums_report', :on => :member
      get 'forums_topics_list', :on => :member
      get 'planet_report', :on => :member
      get 'dot_report', :on => :member
      get 'wiki_report', :on => :member
      get 'builds_report', :on => :member
    end

    get "home/index"

    resources :news

    match '/:locale' => 'home#index', via: [:get, :post]
    root :to => 'home#index'
  end

end

app/views/kde/_side_bar.html.erb
<li class="list-header"><%= t('project').upcase %></li>
<li<%=raw " class='active'" if current_page?(kde_path) %>><%= link_to t('general_kde'), kde_path %></li>
<hr>
<li class="list-header"><%= t('commits').upcase %></li>
<li<%=raw " class='active'" if current_page?(kde_commits_report_path) %>><%= link_to t('commits_report'), kde_commits_report_path %></li>
<hr>
<li class="list-header"><%= t('mailing_lists').upcase %></li>
<li<%=raw " class='active'" if current_page?(kde_mailing_lists_report_path) %>><%= link_to t('mailing_lists_report'), kde_mailing_lists_report_path %></li>
<hr>
<li class="list-header"><%= t('irc_channels').upcase %></li>
<li<%=raw " class='active'" if current_page?(kde_irc_channels_report_path) %>><%= link_to t('irc_channels_report'), kde_irc_channels_report_path %></li>

app/views/kde/commits_report.html.erb
<% content_for(:title,t('commits_report') + " " + t('for') + t('general_kde') ) %>
<div class="page-header">
  <h1>
	<%= t('commits_report') + " " + t('for') + t('general_kde') %>
  </h1>
</div>
<div class="row">
	<div class = "span9">
		<%= render_objects_chart "commits" %>
		<%= render_doers_chart "commits" %>
		<% @project.drawables["commits"].keys.each do |to_plot| %>
			<%= render_commits_charts "commits",to_plot %>
		<% end %>	
	</div>
	<div class = "span3">
		<div class="well sidebar-nav">
			<ul class="nav nav-list">
				<%= render 'side_bar' %>
			</ul>
		</div>
	</div>				
</div>
<% content_for :styles do %>
	.tab-content > .tab-pane {
	    display: block;    /* undo display:none          */
	    height: 0;         /* height:0 is also invisible */ 
	    overflow: hidden;  /* no-overflow                */
	}
	.tab-content > .active {
	    height: auto;      /* let the content decide it  */
	}
<% end %>
<% content_for :scripts do %>
	<%= javascript_include_tag 'highstock.js' %>
<% end %>

app/views/kde/index.html.erb
<% content_for(:title, t('general_kde')) %>
<div class="page-header">
  <h1>
	<%= t('general_kde') %>
  </h1>
</div>

<div class="row">
	<div class = "span9">
		<p></p>
	</div>
	<div class = "span3">
		<div class="well sidebar-nav">
			<ul class="nav nav-list">
				<%= render 'side_bar' %>
			</ul>
		</div>
	</div>				
</div>

app/views/kde/irc_channels_report.html.erb
<% content_for(:title,t('irc_channels_report') + " " + t('for') + @project.title) %>
<div class="page-header">
  <%= render partial: 'top_bar_for_single_project', locals: { back_link: project_path(@project) } %>
  <h1>
	<%= t('irc_channels_report') + " " + t('for') + @project.title %>
  </h1>
</div>
<div class="row">
	<div class = "span9">
		<%= render_objects_chart "irc_messages" %>
		<%= render_doers_chart "irc_messages" %>
		<% @project.drawables["irc_messages"].keys.each do |to_plot| %>
			<%= render_commits_charts "irc_messages",to_plot %>
		<% end %>	
	</div>
	<div class = "span3">
		<div class="well sidebar-nav">
			<ul class="nav nav-list">
				<%= render 'side_bar' %>
			</ul>
		</div>
	</div>				
</div>
<% content_for :styles do %>
	.tab-content > .tab-pane {
	    display: block;    /* undo display:none          */
	    height: 0;         /* height:0 is also invisible */ 
	    overflow: hidden;  /* no-overflow                */
	}
	.tab-content > .active {
	    height: auto;      /* let the content decide it  */
	}
<% end %>
<% content_for :scripts do %>
	<%= javascript_include_tag 'highstock.js' %>
<% end %>

app/views/kde/mailing_lists_report.html.erb
<% content_for(:title, t('mailing_lists_report') + " " + t('for') + @project.title ) %>
<div class="page-header">
  <%= render partial: 'top_bar_for_single_project', locals: { back_link: project_path(@project) } %>
  <h1>
	<%= t('mailing_lists_report') + " " + t('for') + @project.title %>
  </h1>
</div>
<div class="row">
	<div class = "span9">
		<%= render_objects_chart "mailing_messages" %>
		<%= render_doers_chart "mailing_messages" %>
		<% @project.drawables["mailing_messages"].keys.each do |to_plot| %>
			<%= render_commits_charts "mailing_messages",to_plot %>
		<% end %>	
	</div>
	<div class = "span3">
		<div class="well sidebar-nav">
			<ul class="nav nav-list">
				<%= render 'side_bar' %>
			</ul>
		</div>
	</div>				
</div>
<% content_for :styles do %>
	.tab-content > .tab-pane {
	    display: block;    /* undo display:none          */
	    height: 0;         /* height:0 is also invisible */ 
	    overflow: hidden;  /* no-overflow                */
	}
	.tab-content > .active {
	    height: auto;      /* let the content decide it  */
	}
<% end %>
<% content_for :scripts do %>
	<%= javascript_include_tag 'highstock.js' %>
<% end %>