config/routes.rb
Reports::Application.routes.draw do

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      get '/bug/:bug_id', to: 'projects#bug_info'
      get '/commit', to: 'projects#commit_info'
      get '/shortlog', to: 'projects#shortlog'
      resources :projects do
        get 'bugs_report', :on => :member
        get 'bugs_list', :on => :member
        get 'commits_report', :on => :member
        get 'commits_list', :on => :member
        get 'mailing_lists_report', :on => :member
        get 'messages_list', :on => :member
        get 'messages_of_month', :on => :member
        get 'message', :on => :member
        get 'project_report', :on => :member
        get 'irc_channels_report', :on => :member
      end
    end
  end

  scope "(:locale)" do
    get "admin/index"

    get "admin/", to: 'admin#index'

    get "admin/control_user"

    get '/bug/:bug_id', to: 'projects#bug_info'

    get '/commit', to: 'projects#commit_info'

    get '/shortlog', to: 'projects#shortlog'

    devise_for :users

    resources :custom_reports do
      Constants::TYPES_TO_REPORT_TITLES.values.each do |name|
        get "#{name}_report", :on => :member
      end
    end

    get 'kde/', to: 'kde#index', as: :kde
    get 'kde/commits_report', to: 'kde#commits_report', as: :kde_commits_report
    get 'kde/mailing_lists_report', to: 'kde#mailing_lists_report', as: :kde_mailing_lists_report
    get 'kde/irc_channels_report', to: 'kde#irc_channels_report', as: :kde_irc_channels_report

    resources :projects do
      get 'bugs_report', :on => :member
      get 'bugs_list', :on => :member
      get 'bug/:bug_id', :on => :member, :as => :bug, to: 'projects#bug_info'
      get 'repository/:product/:branch/:directory', :on => :member, to: 'projects#repository',as: :repo_path , product: /.+\.git/, directory: /.+/, branch: /[^\/]+/
      get 'repository/:product(/:branch)', :on => :member, to: 'projects#repository',as: :full_repository, product: /.+\.git/, branch: /[^\/]+/
      get 'repository', :on => :member
      get 'blob/:product/:sha/:blob', :on => :member, to: 'projects#show_blob', as: :blob , product: /.+\.git/, blob: /.+/
      get 'commits_report', :on => :member
      get 'commits_per_day', :on => :member
      get 'review_requests_report', :on => :member
      get 'commits_list/:product', :on => :member , to: 'projects#commits_list', product: /.+\.git/
      get 'commits_list', :on => :member
      get 'commit/:product:commit_sha', to: 'projects#commit_info', :on => :member , as: :commit, product: /.+\.git/
      get 'product/:product/branch/*branch', to: 'projects#branch', on: :member, as: :branch, product: /.+\.git/, branch: /.+/
      get 'mailing_lists_report', :on => :member
      get 'mailing_messages_per_day', :on => :member
      get 'messages_list', :on => :member
      get 'messages_list/:mlist/:month/:index', on: :member, to: 'projects#message', as: :message, mlist: /.+\.mbox/
      get 'messages_list/:mlist/:month', on: :member, to: 'projects#messages_of_month', as: :messages_of_month, mlist: /.+\.mbox/
      get 'messages_list/:mlist', :on => :member , to: 'projects#messages_list', as: :messages_list_mbox, mlist: /.+\.mbox/
      get 'project_report', :on => :member
      get 'irc_channels_report', :on => :member
      get 'irc_messages_per_day', :on => :member
      get 'facebook_pages_report', :on => :member
      get 'twitter_report', :on => :member
      get 'google_plus_report', :on => :member
      get 'forums_report', :on => :member
      get 'forums_topics_list', :on => :member
      get 'planet_report', :on => :member
      get 'dot_report', :on => :member
      get 'wiki_report', :on => :member
      get 'builds_report', :on => :member
    end

    get "home/index"

    resources :news

    match '/:locale' => 'home#index', via: [:get, :post]
    root :to => 'home#index'
  end

end

app/views/layouts/application.html.erb
<%# encoding: UTF-8 %>
<!DOCTYPE html>
<html <%= "dir=rtl" if !t('ltr') %>>
<head>
  <meta http-equiv="Content-Type" content="text/html;  charset="utf-8">
  <title><%=h yield(:title).force_encoding("utf-8").encode("utf-8",:invalid => :replace) %> - <%= t :kde_reports %></title>
  <link href="//cdn.kde.org/css/bootstrap.css" rel="stylesheet">
  <link href="//cdn.kde.org/css/bootstrap-responsive.css" rel="stylesheet">
  <link href="//cdn.kde.org/css/prettify.css" rel="stylesheet"/>
  <link href="/css/nprogress.css" rel="stylesheet" />
  <style>
        pre {
                white-space: pre-wrap;
        }
        <%=h yield(:styles) %>
  </style>
  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  <script src="//cdn.kde.org/js/prettify.js"></script>
  <%=h yield(:early_load) %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//cdn.kde.org/js/bootstrap.js"></script>
  <script src="//cdn.kde.org/js/bootstrap-neverland.js"></script>
  <script type="text/javascript" src="/js/highstock.js"></script>
  <%= csrf_meta_tags %>
</head>
<body data-spy="scroll">
<div class="navbar navbar-static-top Neverland">
			<div class="navbar-inner">
				<div class="container">
					<ul class="nav pull-right">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<i class="icon-th-list"></i>
								<%= t('kde_links') %>
								<b class="caret"></b>
							</a>

							<ul id="global-nav" class="dropdown-menu"></ul>
						</li>
					</ul>

					<%= link_to '<img src="//cdn.kde.org/img/logo.plain.small.png" alt="" /> '.html_safe + t('kde_reports'), root_url , :class => "brand" %>
				</div>
			</div>
		</div>
<div class="container">
	<% the_request = request.env['HTTP_USER_AGENT'] ||= "" %>
    <% if the_request.include?("konqueror") %>
      <%= content_tag :div, :class => "alert" do %>
        Konqueror browser is not fully supported. You might not be able to see the graphical reports. Consider using <a target="_blank" href="http://rekonq.kde.org/">Rekonq</a> if you want to see them.
      <% end %>
    <% end %>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert #{name == "alert" ? "alert-error" : "alert-success" }" do %>
        <a class="close" data-dismiss="alert" href="#">×</a>
        <%= msg %>
      <% end %>
    <% end %>
      <%= yield %>
      <span id="neverland-footer-placeholder"></span>
            	<div id="footerRow" class="row">
		<div class="navbar navbar-bottom Neverland">
			<div class="navbar-inner">
				<div class="container">
					<ul id="footer-places" class="nav">
						<li>
							<%= link_to '<i class="icon-home icon-white"></i> '.html_safe + t('home'), root_path %>
						</li>
						<li>
							<%= link_to '<i class="icon-book icon-white"></i> '.html_safe + t('projects'), projects_path %>
						</li>
						<li>
							<%= link_to '<i class="icon-book icon-white"></i> '.html_safe + t('kde_community'), (projects_path + "/kde-community") %>
						</li>
						<li>
							<%= link_to '<i class="icon-file icon-white"></i> '.html_safe + t('custom_reports'), custom_reports_path %>
						</li>
					</ul>
					<ul class="nav pull-right">

						<li class="dropdown">
    <a class="dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="#">
        <%= t :language %>
        <b class="caret-up"></b>
    </a>
    <ul class="dropdown-menu bottom-up" role="menu" aria-labelledby="dLabel">
        <li><%= link_to "English", :locale=>'en' %></li>
        <li><%= link_to "العربية".encode('utf-8', :invalid => :replace, :undef => :replace), :locale=>'ar' %></li>
    </ul>
</li>


						<% if user_signed_in? %>
							<% if can? :index, :admin %>
								<li>
								  <%= link_to(t('admin_panel'), admin_path) %>
								</li>
							<% end %>
						  <li>
						  <%= link_to(t('logout'), destroy_user_session_path, :method => :delete) %>
						  </li>
						<% else %>
						  <li>
						  <%= link_to(t('sign_in'), new_user_session_path)  %>
						  </li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
			      <footer class="Neverland" style="height:70px;">
			      </footer>

</div> <!-- /container -->
<%=h yield(:scripts) %>
<script data-turbolinks-track="true" src="//cdn.kde.org/nav/global-nav.js"></script>
</body>
</html>

app/views/layouts/json_layout.json.erb
{"status": <%= response.status %>,"data": <%= yield %>}

app/views/layouts/xml_layout.xml.erb
<?xml version="1.0" encoding="UTF-8"?><result><status type="integer"><%= response.status %></status><data><%= yield %></data></result>